/* GET all */
export const GET_DEPENDENTS = "GET_DEPENDENTS";
export const GET_DEPENDENTS_SUCCESS = "GET_DEPENDENTS_SUCCESS";
export const GET_DEPENDENTS_ERROR = "GET_DEPENDENTS_ERROR";

/* GET one */
export const GET_DEPENDENT = "GET_DEPENDENT";
export const GET_DEPENDENT_SUCCESS = "GET_DEPENDENT_SUCCESS";
export const GET_DEPENDENT_ERROR = "GET_DEPENDENT_ERROR";

/* POST */
export const POST_DEPENDENT = "POST_DEPENDENT";
export const POST_DEPENDENT_SUCCESS = "POST_DEPENDENT_SUCCESS";
export const POST_DEPENDENT_ERROR = "POST_DEPENDENT_ERROR";

/* UPDATE */
export const UPDATE_DEPENDENT = "UPDATE_DEPENDENT";
export const UPDATE_DEPENDENT_SUCCESS = "UPDATE_DEPENDENT_SUCCESS";
export const UPDATE_DEPENDENT_ERROR = "UPDATE_DEPENDENT_ERROR";

/* DELETE */
export const DELETE_DEPENDENT = "DELETE_DEPENDENT";
export const DELETE_DEPENDENT_SUCCESS = "DELETE_DEPENDENT_SUCCESS";
export const DELETE_DEPENDENT_ERROR = "DELETE_DEPENDENT_ERROR";
